# Generated by Django 4.0.5 on 2022-08-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('kakao_id', models.IntegerField()),
                ('kakao_profile_img', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=50)),
                ('birth_day', models.CharField(max_length=50)),
                ('point', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
