# Generated by Django 4.0.5 on 2022-08-02 23:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=10),
        ),
    ]
