# Generated by Django 4.0.5 on 2022-08-02 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.RemoveField(
            model_name='roomfacility',
            name='name',
        ),
        migrations.RemoveField(
            model_name='roomfacility',
            name='rooms_room_facility',
        ),
        migrations.AddField(
            model_name='roomfacility',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
        migrations.AlterField(
            model_name='room',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
        migrations.AlterModelTable(
            name='roomfacility',
            table='rooms_facilities',
        ),
        migrations.DeleteModel(
            name='RoomsRoomFacility',
        ),
        migrations.AddField(
            model_name='room',
            name='facility',
            field=models.ManyToManyField(through='rooms.RoomFacility', to='rooms.facility'),
        ),
        migrations.AddField(
            model_name='roomfacility',
            name='room_facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.facility'),
            preserve_default=False,
        ),
    ]
