# Generated by Django 4.0.5 on 2022-08-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_facility_remove_roomfacility_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='facility',
            new_name='facilities',
        ),
    ]
